site_name: ML + Data Assimilation

site_url: https://jaeminoh.github.io/ODA
repo_url: https://github.com/jaeminoh/ODA
repo_name: jaeminoh/ODA

theme:
  #favicon: images/favicon.png
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - roamlinks
  - tags
  - bibtex:
      bib_file: "bibliography/library.bib"
      csl_file: "bibliography/ima.csl"

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true


extra:
  analytics:
    provider: google
    property: G-B9XBB4QRXM

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js