[project]
name = "oda"
version = "0.0.1"
description = "offline data assimilation"
readme = "README.md"
requires-python ="~=3.11"
authors = [
  {name = "Jaemin Oh", email = "jaeminoh.math@gmail.com"},
]
urls = {repository = "https://github.com/jaeminoh/ODA" }

[tool.setuptools]
packages = ["oda"]

[tool.ruff.lint]
ignore = ["F722"]